// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "ipgroup.hpp"

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

namespace openstack
{
  namespace xml
  {
    // SharedIpGroup_
    // 

    const ::xml_schema::Type* SharedIpGroup_::
    _value () const
    {
      return &this->value_.get ();
    }

    ::xml_schema::Type* SharedIpGroup_::
    _value ()
    {
      return &this->value_.get ();
    }

    SharedIpGroup_::
    SharedIpGroup_ (const ValueType& x)
    : value_ (x, 0, 0)
    {
    }

    SharedIpGroup_::
    SharedIpGroup_ (::std::auto_ptr< ValueType > p)
    : value_ (p, 0, 0)
    {
    }

    SharedIpGroup_::
    SharedIpGroup_ (const ::xercesc::DOMElement& e, ::xml_schema::Flags f)
    : value_ (f, 0)
    {
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == name_ && n.namespace_ () == namespace__)
        this->value_.set (ValueTraits::create (e, f, 0));
      else
        throw ::xsd::cxx::tree::unexpected_element < char > (
          n.name (), n.namespace_ (),
          name_, namespace__);
    }

    SharedIpGroup_::
    SharedIpGroup_ (const SharedIpGroup_& x, ::xml_schema::Flags f)
    : ::xml_schema::ElementType (),
      value_ (x.value_, f, 0)
    {
    }

    SharedIpGroup_* SharedIpGroup_::
    _clone (::xml_schema::Flags f) const
    {
      return new class SharedIpGroup_ (*this, f);
    }

    const ::std::string& SharedIpGroup_::
    name ()
    {
      return name_;
    }

    const ::std::string& SharedIpGroup_::
    namespace_ ()
    {
      return namespace__;
    }

    const ::std::string& SharedIpGroup_::
    _name () const
    {
      return name_;
    }

    const ::std::string& SharedIpGroup_::
    _namespace () const
    {
      return namespace__;
    }

    const ::std::string SharedIpGroup_::
    name_ ("sharedIpGroup");

    const ::std::string SharedIpGroup_::
    namespace__ ("http://docs.rackspacecloud.com/servers/api/v1.0");

    SharedIpGroup_::
    ~SharedIpGroup_ ()
    {
    }

    static 
    const ::xsd::cxx::tree::parser_init< SharedIpGroup_, char, ::xml_schema::Type >
    _xsd_SharedIpGroup__parser_init (SharedIpGroup_::name (), SharedIpGroup_::namespace_ ());

    // SharedIpGroups_
    // 

    const ::xml_schema::Type* SharedIpGroups_::
    _value () const
    {
      return &this->value_.get ();
    }

    ::xml_schema::Type* SharedIpGroups_::
    _value ()
    {
      return &this->value_.get ();
    }

    SharedIpGroups_::
    SharedIpGroups_ (const ValueType& x)
    : value_ (x, 0, 0)
    {
    }

    SharedIpGroups_::
    SharedIpGroups_ (::std::auto_ptr< ValueType > p)
    : value_ (p, 0, 0)
    {
    }

    SharedIpGroups_::
    SharedIpGroups_ (const ::xercesc::DOMElement& e, ::xml_schema::Flags f)
    : value_ (f, 0)
    {
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == name_ && n.namespace_ () == namespace__)
        this->value_.set (ValueTraits::create (e, f, 0));
      else
        throw ::xsd::cxx::tree::unexpected_element < char > (
          n.name (), n.namespace_ (),
          name_, namespace__);
    }

    SharedIpGroups_::
    SharedIpGroups_ (const SharedIpGroups_& x, ::xml_schema::Flags f)
    : ::xml_schema::ElementType (),
      value_ (x.value_, f, 0)
    {
    }

    SharedIpGroups_* SharedIpGroups_::
    _clone (::xml_schema::Flags f) const
    {
      return new class SharedIpGroups_ (*this, f);
    }

    const ::std::string& SharedIpGroups_::
    name ()
    {
      return name_;
    }

    const ::std::string& SharedIpGroups_::
    namespace_ ()
    {
      return namespace__;
    }

    const ::std::string& SharedIpGroups_::
    _name () const
    {
      return name_;
    }

    const ::std::string& SharedIpGroups_::
    _namespace () const
    {
      return namespace__;
    }

    const ::std::string SharedIpGroups_::
    name_ ("sharedIpGroups");

    const ::std::string SharedIpGroups_::
    namespace__ ("http://docs.rackspacecloud.com/servers/api/v1.0");

    SharedIpGroups_::
    ~SharedIpGroups_ ()
    {
    }

    static 
    const ::xsd::cxx::tree::parser_init< SharedIpGroups_, char, ::xml_schema::Type >
    _xsd_SharedIpGroups__parser_init (SharedIpGroups_::name (), SharedIpGroups_::namespace_ ());

    // SharedIpGroup
    //

    SharedIpGroup::
    SharedIpGroup (const NameType& name)
    : ::xml_schema::Type (),
      server_ (::xml_schema::Flags (), this),
      servers_ (::xml_schema::Flags (), this),
      id_ (::xml_schema::Flags (), this),
      name_ (name, ::xml_schema::Flags (), this)
    {
    }

    SharedIpGroup::
    SharedIpGroup (const SharedIpGroup& x,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      server_ (x.server_, f, this),
      servers_ (x.servers_, f, this),
      id_ (x.id_, f, this),
      name_ (x.name_, f, this)
    {
    }

    SharedIpGroup::
    SharedIpGroup (const ::xercesc::DOMElement& e,
                   ::xml_schema::Flags f,
                   ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      server_ (f, this),
      servers_ (f, this),
      id_ (f, this),
      name_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
        this->parse (p, f);
      }
    }

    void SharedIpGroup::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_elements (); p.next_element ())
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // server
        //
        {
          ::xsd::cxx::tree::type_factory_map< char >& tfm (
            ::xsd::cxx::tree::type_factory_map_instance< 0, char > ());

          ::std::auto_ptr< ::xsd::cxx::tree::type > tmp (
            tfm.create (
              "server",
              "http://docs.rackspacecloud.com/servers/api/v1.0",
              &::xsd::cxx::tree::factory_impl< ServerType >,
              false, true, i, n, f, this));

          if (tmp.get () != 0)
          {
            if (!this->server_)
            {
              ::std::auto_ptr< ServerType > r (
                dynamic_cast< ServerType* > (tmp.get ()));

              if (r.get ())
                tmp.release ();
              else
                throw ::xsd::cxx::tree::not_derived< char > ();

              this->server_.set (r);
              continue;
            }
          }
        }

        // servers
        //
        {
          ::xsd::cxx::tree::type_factory_map< char >& tfm (
            ::xsd::cxx::tree::type_factory_map_instance< 0, char > ());

          ::std::auto_ptr< ::xsd::cxx::tree::type > tmp (
            tfm.create (
              "servers",
              "http://docs.rackspacecloud.com/servers/api/v1.0",
              &::xsd::cxx::tree::factory_impl< ServersType >,
              false, true, i, n, f, this));

          if (tmp.get () != 0)
          {
            if (!this->servers_)
            {
              ::std::auto_ptr< ServersType > r (
                dynamic_cast< ServersType* > (tmp.get ()));

              if (r.get ())
                tmp.release ();
              else
                throw ::xsd::cxx::tree::not_derived< char > ();

              this->servers_.set (r);
              continue;
            }
          }
        }

        break;
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "id" && n.namespace_ ().empty ())
        {
          this->id_.set (IdTraits::create (i, f, this));
          continue;
        }

        if (n.name () == "name" && n.namespace_ ().empty ())
        {
          ::std::auto_ptr< NameType > r (
            NameTraits::create (i, f, this));

          this->name_.set (r);
          continue;
        }
      }

      if (!name_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< char > (
          "name",
          "");
      }
    }

    SharedIpGroup* SharedIpGroup::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class SharedIpGroup (*this, f, c);
    }

    SharedIpGroup::
    ~SharedIpGroup ()
    {
    }

    static
    const ::xsd::cxx::tree::type_factory_initializer< 0, char, SharedIpGroup >
    _xsd_SharedIpGroup_type_factory_init (
      "SharedIpGroup",
      "http://docs.rackspacecloud.com/servers/api/v1.0");

    // SharedIpGroups
    //

    SharedIpGroups::
    SharedIpGroups ()
    : ::xml_schema::Type (),
      sharedIpGroup_ (::xml_schema::Flags (), this)
    {
    }

    SharedIpGroups::
    SharedIpGroups (const SharedIpGroups& x,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      sharedIpGroup_ (x.sharedIpGroup_, f, this)
    {
    }

    SharedIpGroups::
    SharedIpGroups (const ::xercesc::DOMElement& e,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      sharedIpGroup_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
        this->parse (p, f);
      }
    }

    void SharedIpGroups::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_elements (); p.next_element ())
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // sharedIpGroup
        //
        {
          ::xsd::cxx::tree::type_factory_map< char >& tfm (
            ::xsd::cxx::tree::type_factory_map_instance< 0, char > ());

          ::std::auto_ptr< ::xsd::cxx::tree::type > tmp (
            tfm.create (
              "sharedIpGroup",
              "http://docs.rackspacecloud.com/servers/api/v1.0",
              &::xsd::cxx::tree::factory_impl< SharedIpGroupType >,
              false, true, i, n, f, this));

          if (tmp.get () != 0)
          {
            ::std::auto_ptr< SharedIpGroupType > r (
              dynamic_cast< SharedIpGroupType* > (tmp.get ()));

            if (r.get ())
              tmp.release ();
            else
              throw ::xsd::cxx::tree::not_derived< char > ();

            this->sharedIpGroup_.push_back (r);
            continue;
          }
        }

        break;
      }
    }

    SharedIpGroups* SharedIpGroups::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class SharedIpGroups (*this, f, c);
    }

    SharedIpGroups::
    ~SharedIpGroups ()
    {
    }

    static
    const ::xsd::cxx::tree::type_factory_initializer< 0, char, SharedIpGroups >
    _xsd_SharedIpGroups_type_factory_init (
      "SharedIpGroups",
      "http://docs.rackspacecloud.com/servers/api/v1.0");

    // ServerIDList
    //

    ServerIDList::
    ServerIDList ()
    : ::xml_schema::Type (),
      server_ (::xml_schema::Flags (), this)
    {
    }

    ServerIDList::
    ServerIDList (const ServerIDList& x,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      server_ (x.server_, f, this)
    {
    }

    ServerIDList::
    ServerIDList (const ::xercesc::DOMElement& e,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      server_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
        this->parse (p, f);
      }
    }

    void ServerIDList::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_elements (); p.next_element ())
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // server
        //
        {
          ::xsd::cxx::tree::type_factory_map< char >& tfm (
            ::xsd::cxx::tree::type_factory_map_instance< 0, char > ());

          ::std::auto_ptr< ::xsd::cxx::tree::type > tmp (
            tfm.create (
              "server",
              "http://docs.rackspacecloud.com/servers/api/v1.0",
              &::xsd::cxx::tree::factory_impl< ServerType >,
              false, true, i, n, f, this));

          if (tmp.get () != 0)
          {
            ::std::auto_ptr< ServerType > r (
              dynamic_cast< ServerType* > (tmp.get ()));

            if (r.get ())
              tmp.release ();
            else
              throw ::xsd::cxx::tree::not_derived< char > ();

            this->server_.push_back (r);
            continue;
          }
        }

        break;
      }
    }

    ServerIDList* ServerIDList::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class ServerIDList (*this, f, c);
    }

    ServerIDList::
    ~ServerIDList ()
    {
    }

    static
    const ::xsd::cxx::tree::type_factory_initializer< 0, char, ServerIDList >
    _xsd_ServerIDList_type_factory_init (
      "ServerIDList",
      "http://docs.rackspacecloud.com/servers/api/v1.0");

    // ServerID
    //

    ServerID::
    ServerID (const IdType& id)
    : ::xml_schema::Type (),
      id_ (id, ::xml_schema::Flags (), this)
    {
    }

    ServerID::
    ServerID (const ServerID& x,
              ::xml_schema::Flags f,
              ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      id_ (x.id_, f, this)
    {
    }

    ServerID::
    ServerID (const ::xercesc::DOMElement& e,
              ::xml_schema::Flags f,
              ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      id_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, false, true);
        this->parse (p, f);
      }
    }

    void ServerID::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "id" && n.namespace_ ().empty ())
        {
          this->id_.set (IdTraits::create (i, f, this));
          continue;
        }
      }

      if (!id_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< char > (
          "id",
          "");
      }
    }

    ServerID* ServerID::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class ServerID (*this, f, c);
    }

    ServerID::
    ~ServerID ()
    {
    }

    static
    const ::xsd::cxx::tree::type_factory_initializer< 0, char, ServerID >
    _xsd_ServerID_type_factory_init (
      "ServerID",
      "http://docs.rackspacecloud.com/servers/api/v1.0");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

